# secrets.toml
# openai_api_key = "your_openai_api_key_here"
openai_api_key = "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"
